version: '2'

networks:
  bibbox-default-network:
    external: true

services:

  §§INSTANCE-webapi-db:
    image: postgres:11
    container_name: §§INSTANCE-webapi-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=§§POSTGRES_DATABASE_PASSWORD
      - POSTGRES_USER=§§POSTGRES_DATABASE_USER
      - POSTGRES_DB=ohdsi
    networks:
      - bibbox-default-network
    volumes_from:
      - §§INSTANCE-ohdsi-data

  §§INSTANCE-webapi:
    build:
      context: ./images/webapi
      dockerfile: Dockerfile
    container_name: §§INSTANCE-webapi
    restart: unless-stopped
    environment:
      - WEBAPI_URL=http://192.168.1.8:8080
      - datasource_driverClassName=org.postgresql.Driver
      - datasource_url=jdbc:postgresql://webapi-db:5432/ohdsi
      - datasource_username=§§POSTGRES_DATABASE_USER
      - datasource_password=§§POSTGRES_DATABASE_PASSWORD
      - spring.jpa.properties.hibernate.default_schema=ohdsi
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.batch.repository.tableprefix=ohdsi.BATCH_
      - flyway_datasource_driverClassName=org.postgresql.Driver
      - flyway_datasource_url=jdbc:postgresql://webapi-db:5432/ohdsi
      - flyway_schemas=ohdsi
      - flyway.placeholders.ohdsiSchema=ohdsi
      - flyway_datasource_username=§§POSTGRES_DATABASE_USER
      - flyway_datasource_password=§§POSTGRES_DATABASE_PASSWORD
      - flyway.locations=classpath:db/migration/postgresql
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-webapi-db:webapi-db
    ports:
      - "§§PORTAPI:8080"
    depends_on:
      - §§INSTANCE-webapi-db
      - §§INSTANCE-ohdsi-data

  §§INSTANCE-ohdsi-data:
    image: busybox
    container_name: §§INSTANCE-app-data
    volumes:
      - ./data/ohdsi/postgresql/data:/var/lib/postgresql/data
      - ./setup/docker-entrypoint-initdb.d:docker-entrypoint-initdb.d





